# Generated by Django 3.1.7 on 2021-03-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicepalapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='beats',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='sections',
            name='division',
            field=models.IntegerField(default=4),
        ),
    ]
