# Generated by Django 3.1.3 on 2021-03-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicepalapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitions',
            unique_together={('created_by', 'section')},
        ),
    ]
