# Generated by Django 3.1.7 on 2021-03-10 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practicepalapi', '0004_auto_20210310_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_users', related_query_name='song_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
