# Generated by Django 3.1.7 on 2021-03-10 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practicepalapi', '0005_auto_20210310_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs_appusers', related_query_name='songs_appuser', to='practicepalapi.appusers'),
        ),
    ]
